version: '3'
services:
        jekyll-serve:
                image: jekyll/jekyll
                volumes:
                        - '.:/serve/jekyll'
                ports:
                        - 4000:4000
                command: 'jekyll serve'
